// <auto-generated />
using System;
using KenshuServiceForms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KenshuServiceForms.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("KenshuServiceForms.T_Charge", b =>
                {
                    b.Property<int>("charge_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("charge_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("startDate")
                        .HasColumnType("TEXT");

                    b.HasKey("charge_id");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("KenshuServiceForms.T_Member", b =>
                {
                    b.Property<int>("member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("payment_method")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("TEXT");

                    b.HasKey("member_id");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
